language: java
#matrix:
#  include:
#    - name: "Linux"
#      os: linux
#      dist: xenial
#    - name: "MacOS"
#      os: osx
#      osx_image: xcode9.4
#    - name: "Windows"
#      os: windows
#      # Help : https://travis-ci.community/c/environments/windows
#      # Pre-installed packages: https://docs.travis-ci.com/user/reference/windows/
#      # use `choco` command
jdk:
  - oraclejdk8
#  - oraclejdk11
#  - openjdk10
#  - openjdk11

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD
  - ant dist

script: ant test
