language: java
install: 
  - git clone https://github.com/Funz/funz-profile $TRAVIS_REPO_SLUG/..
  - cd $TRAVIS_REPO_SLUG
  - ant dist
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
script: ant test
